CREATE TABLE moex_companies(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(300) NOT NULL,
    ticker VARCHAR(8) NOT NULL,
    figi VARCHAR(15) NOT NULL
);

CREATE INDEX idx_name_hash ON moex_companies USING HASH (name);
CREATE INDEX idx_ticker_hash ON moex_companies USING HASH (ticker);
CREATE INDEX idx_figi_hash ON moex_companies USING HASH (figi);