server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: api-t-connector
          uri: ${uri.api.app}
          predicates:
            - Path=/connector/public/api/v1/**
        - id: definition-of-anomaly
          uri: ${uri.define.anomaly}
          predicates:
            - Path=/anomaly/public/api/v1/**
        - id: guide
          uri: ${uri.company.info}
          predicates:
            - Path=/company/**


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /openapi.json
