server:
  port: 8090

spring:
  application:
    name: definition-of-anomaly
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:init_table.sql
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port} # maybe make problems
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
    template:
      queue: ${rabbitmq.template.queue}
      exchange: ${rabbitmq.template.exchange}
      routing-key: ${rabbitmq.template.routing.key}


service:
  api:
    url: ${api.app.url}
  guide:
    url: ${guide.url}
  telegram:
    uri: ${telegram-uri}