FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src
#COPY .env .

RUN mvn dependency:go-offline -B

RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /app

#COPY .env .

COPY --from=build /app/target/definition-of-anomaly-0.0.1-SNAPSHOT.jar .

EXPOSE 8090

# Установка переменных окружения
CMD  java -jar definition-of-anomaly-0.0.1-SNAPSHOT.jar

